# -----
# Created Date: 2021/2/22
# Author: Hanjing Wang
# -----
# Last Modified:
# Modified By:
# -----
# Copyright (c) 2020 MARL @ SJTU
# -----

version: '3'
services:

  mongo:
    image: mongo
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - $HOME/malib-mongo:/data/db
    expose:
      - 27017
    environment:
      MONGO_INITDB_DATABASE: expr
    network_mode: host