name: MAlib CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  venv_dir: .venv
jobs:
  test-formatting:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.7.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.9
      - name: Run Black code formatter
        run: |
          cd $GITHUB_WORKSPACE
          pip install --upgrade pip
          pip install 'black==20.8b1'
          black --check .

  test-requirements:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
