name: MAlib CI Pull Request

on:
  push:
    branches:
      - disabled

env:
  venv_dir: .venv
jobs:
  test-benchmark:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1.2.0

